# Generated by Django 4.2.5 on 2023-10-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='football',
            name='email',
        ),
        migrations.AddField(
            model_name='football',
            name='jersey_no',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
